version: 2

builds:
  - id: dist02cyclonedx
    main: ./cmd/distro2go/main.go
    goos:
      - linux
    goarch:
      - amd64

nfpms:
  - id: dist02cyclonedx
    maintainer: Jan Syren <jan.syren@gmail.com>
    license: "GPL-3.0"
    formats:
      - deb
      - rpm
    bindir: /usr/local/bin
    contents:
      - src: spdx-data/spdx.schema.json_sample
        dst: /var/lib/distro2go/spdx.schema.json
      - src: config/dist02cyclonedx.yaml
        dst: /etc/dist02cyclonedx.yaml

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'