name: Release

on:
  workflow_dispatch:  # Manual trigger
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, ubuntu-24.04, 'rockylinux/rockylinux:8', 'rockylinux/rockylinux:9']
        include:
          - os: 'rockylinux/rockylinux:8'
            goos: linux
            goarch: amd64
            env:
              CGO_ENABLED: 0
          - os: 'rockylinux/rockylinux:9'
            goos: linux
            goarch: amd64
            env:
                CGO_ENABLED: "0"
          - os: ubuntu-20.04
            goos: linux
            goarch: amd64
          - os: ubuntu-22.04
            goos: linux
            goarch: amd64
          - os: ubuntu-24.04
            goos: linux
            goarch: amd64

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.1'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.BUILD_TOKEN }}
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: ${{ matrix.env.CGO_ENABLED || '1' }}
