name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  # packages: write
  # issues: write
  # id-token: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4  # Specify v4 for checkout

      - name: Set up Go
        uses: actions/setup-go@v5  # Specify a version for setup-go
        with:
          go-version: '1.23.1'  # VERY IMPORTANT: Pin Go version

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          # 'latest', 'nightly', or a semver
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.BUILD_TOKEN }}
