name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23.1'

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest

      - name: Run GoReleaser
        env:
          GITHUB_TOKEN: ${{ secrets.BUILD_TOKEN }}
        run: goreleaser release
